// Generate from the migrated PostgreSQL catalog without needing cloud credentials.
import { writeFileSync } from "node:fs";
import { format } from "prettier";
import { database } from "../tests/helpers/database";
async function main() {
  const db = await database();
  try {
    const tables = (
      await db.query<{ table_name: string }>(
        "select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by table_name",
      )
    ).rows;
    const names = new Set(tables.map((t) => t.table_name));
    function type(sql: string): string {
      if (sql.endsWith("[]")) return `(${type(sql.slice(0, -2))})[]`;
      if (names.has(sql))
        return `Database["public"]["Tables"][${JSON.stringify(sql)}]["Row"]`;
      if (["json", "jsonb"].includes(sql)) return "Json";
      if (sql === "boolean") return "boolean";
      if (
        [
          "integer",
          "bigint",
          "smallint",
          "numeric",
          "real",
          "double precision",
          "oid",
        ].includes(sql)
      )
        return "number";
      if (sql === "void") return "undefined";
      return "string";
    }
    let output =
      "// Generated by backend/scripts/generate-database-types.ts. Do not edit.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n";
    for (const { table_name } of tables) {
      const columns = (
        await db.query<{
          name: string;
          type: string;
          nullable: boolean;
          optional: boolean;
          generated: boolean;
        }>(
          `select a.attname as name,format_type(a.atttypid,a.atttypmod) as type,not a.attnotnull as nullable,(d.oid is not null or a.attidentity<>'') as optional,a.attgenerated<>'' as generated from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where n.nspname='public' and c.relname=$1 and a.attnum>0 and not a.attisdropped order by a.attnum`,
          [table_name],
        )
      ).rows;
      output += JSON.stringify(table_name) + ": {\n";
      for (const mode of ["Row", "Insert", "Update"]) {
        output += mode + ": {\n";
        for (const c of columns)
          output +=
            JSON.stringify(c.name) +
            (mode === "Update" ||
            (mode === "Insert" && (c.optional || c.nullable || c.generated))
              ? "?"
              : "") +
            ": " +
            (c.generated && mode !== "Row"
              ? "never"
              : type(c.type) + (c.nullable ? " | null" : "")) +
            ";\n";
        output += "};\n";
      }
      output += "Relationships: [];\n};\n";
    }
    output += "}; Views: Record<never, never>; Functions: {\n";
    const functions = (
      await db.query<{
        name: string;
        args: { name: string; type: string }[];
        result: string;
        many: boolean;
      }>(
        `select p.proname as name,coalesce((select jsonb_agg(jsonb_build_object('name',p.proargnames[i],'type',format_type(p.proargtypes[i-1],null))) from generate_series(1,p.pronargs) i),'[]') as args,format_type(p.prorettype,null) as result,p.proretset as many from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prorettype<>'trigger'::regtype order by p.proname`,
      )
    ).rows;
    for (const f of functions)
      output +=
        JSON.stringify(f.name) +
        ": { Args: " +
        (f.args.length
          ? "{" +
            f.args
              .map(
                (a) => JSON.stringify(a.name) + ": " + type(a.type) + " | null",
              )
              .join(";") +
            "}"
          : "Record<never, never>") +
        "; Returns: " +
        type(f.result) +
        (f.many ? "[]" : "") +
        " };\n";
    output +=
      "}; Enums: Record<never, never>; CompositeTypes: Record<never, never>; }; };\n";
    writeFileSync(
      "../packages/contracts/src/database.ts",
      await format(output, { parser: "typescript" }),
    );
  } finally {
    await db.close();
  }
}
void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
